### PR TITLE
Update en_US.js

### PR DESCRIPTION
**Pull request by webcaetano**
Hi, 
You idea is awesome, it have potential.

Hope you like my PR.

I'll leave a small suggestion. Please don't understand it as a demand. If you like i could help doing it.

Almost all data from this project are stored on `en_US.js`
So, if you pretend to keep it small , that's fine. But this structure don't scale.
If you plan to scale this. We should split it in folders, in a alphabetical order.

E.g.

```
- en_US (folder)
  - Nouns (folder)
    - Animal (file)
    - Monster (file)
    - Weapon (file)
  - Place (folder)
    - Building (file)
    - Natural (file)
```

etc

### CODE REVIEW

**Comment by svenanders** [comment]
Hi! Thank you :)

What you're suggesting is actually very close to how it's actually compiled, except it's not so granular that every group has its single file. 

There's a folder called resources. When you _cd_ into that, you'll see a few parsers and a submodule (https://github.com/svenanders/Rantionary > RantVocab). I think the submodule config is actually missing from the repo, so I'll add it and update the README. When you run *perl parseAll.pl*, the Rantionary files will be parsed and converted to JavaScript to the _out/_ folder, and then the contents of _out/_ is concatenated to _en_US.js_.

This is kept separate just for the reason that you're pointing out. It doesn't scale to lump everything together in a single dictionary. Also, sometimes you want different dictionaries. The idea is that you should be able to just load rant-core and whatever dictionary that you want. It's very easy, simply remove the hook to _en_US_ and set it up so that you call rantjs with a custom dic. For instance, a year ago I started developing an RPG game using rantjs to spice up the conversations, and I used a small custom dictionary for that. I had to put development on hold due to other commitments though (work...).

Anyway, let me know what you think, and of course, I'm happy to take PRs.

**Comment by webcaetano** [comment]
I didn't installed it. I edited right from github.
Also i didn't know the https://github.com/RantLang/Rantionary and https://github.com/TheBerkin/Rant It make me feel falling in a parachute over your repo... this tools look so good and usefull.

I'm a gaming developer too , i saw te potential on this for gaming developing.
It could be very usefull in so many ways. 

So basically what i'm asking is already done. 
And what i edited is not a source code, but a output file from a build process.
You repo is Rant a hub for nodejs. and maybe Futher browsers.

If i want to populate the dictionary i need to contrib to [RantLang](https://github.com/RantLang/Rantionary) or [svenanders](https://github.com/svenanders/Rantionary) ?

Thanks for your time. 
Keep the good work.

**Comment by svenanders** [comment]
Great to hear :) 

For populating the official dictionary, I think it's definitely better to contribute to RantLang Rantionary. I do merges every now and then (though I'll admit it's been a while since the last time) in order to keep up. I'll make sure to set aside time to do a new merge ASAP.

**Comment by TheBerkin** [comment]
Rant dev here.

I should note that we will be revising the table format for the upcoming v3.0. If you're planning on writing a DIC file parser, this is something to keep in mind.

**Comment by svenanders** [comment]
Aha, thanks for letting me know. I'll pop over to Rant proper and pay attention to the upcoming changes! :)

**Comment by webcaetano** [comment]
@TheBerkin, thanks , should we wait v3.0 come out, or do it before the review?

**Comment by TheBerkin** [comment]
@webcaetano The new table format will use a separate file extension, as it's going to be significantly different from the current format. This means it's safe to write a DIC parser and not have to worry about forward-compatibility. The new format will need a separate parser.

**Comment by webcaetano** [comment]
@TheBerkin what will be the next format? 
The 3.0 have an dev branch?

**Comment by TheBerkin** [comment]
Technically yes, we do have a v3 branch, but we started using a separate branch late into the development cycle for 3.0. Therefore, it isn't representative of all the commits related to the new version.

**Pull request closed without merging**
